
         input Python , java,linux,hack,
         input ,pro,invisible,legend,thanos
         Legend.(edit_legend-hack.)()).
 legendhacker.>
legendhacker(input(str(invisible.send.messege.?
}
               { legendhacker.invisible.edit(input)(*)()
       legend = str(hack).edit 
                  hack = edit.invisible (op.send)))))))
    hack.send ?
havk hvnlhfgsjjjyhfdytuuyouojjajdj787wfmuf7sf7f="
     

hack= (str(LEGEND.INVISIBLE)"/?
print(hack).send=5267090352.)):}
[HACKERS)
[]L{}
}
